### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by hicham-elmansouri** [afawcett/flowtoolbelt#2]
Hi,
When deploying, an error is raised something like 'TestA' is an unknown type. The error is raised because the package contains the generated class with an example of flow. The 'newInstance' method should be empty.

The workaround is to create a flow named 'TestA' before deplying the package.

Thanks for this good tool...

**Comment by afawcett** [comment]
A yes, the test Flow should really be in the repo. You can in the meantime install via the managed package. Using the Deploy to Salesforce button is only if you plan to change the code and/or contribute back to this project. Thanks for heads up either way. 👍

**Comment by afawcett** [comment]
Fixed

**Comment by hicham-elmansouri** [comment]
Cool thanks Andrew...
Hicham El Mansouri
