### ISSUE TITLE
Unable to enter "__c" suffix for Custom Object name in Custom Metadata

### ISSUE THREAD

**Issue by D-McGovern** [afawcett/flowtoolbelt#6]
I'd like to use the dynamic flow component on a custom object, and am prompted to enter the full API name of that object when I open the component in the UI. However, receive the following message when attempting to do so, and am unable to enter "__c" in a custom metadata record:

Errors:
• Custom Metadata Record Name: The Dynamic Flow Component API Name can only contain underscores and alphanumeric characters. It must be unique, begin with a letter, not include spaces, not end with an underscore, and not contain two consecutive underscores.

• The Custom Metadata Record Name field can only contain underscores and alphanumeric characters. It must be unique, begin with a letter, not include spaces, not end with an underscore, and not contain two consecutive underscores.

**Comment by D-McGovern** [comment]
![screen shot 2018-09-19 at 12 43 15 pm](https://user-images.githubusercontent.com/38118812/45767999-a98b3400-bc09-11e8-9b04-ec47833aa48c.png)

**Comment by afawcett** [comment]
Fixed in v2.5
