### ISSUE TITLE
Summer 19 Error Loading Dynamic Flow Component

### ISSUE THREAD

**Issue by Clint-Majors** [afawcett/flowtoolbelt#7]
Since Summer 19 was installed the dynamic flow component is throwing the following error on page load.

Uncaught Error in $A.getCallback() [[object Object]]
Callback failed: serviceComponent://ui.interaction.runtime.components.controllers.FlowRuntimeController/ACTION$runInterview
Callback failed: serviceComponent://ui.interaction.runtime.components.controllers.FlowRuntimeController/ACTION$runInterview
throws at https://mydomain--fullsandbox.lightning.force.com/auraFW/javascript/0Rz6fp7Oruhim-Qzw_AgRQ/aura_prod.js:43:15. Caused by: Error in $A.getCallback() [[object Object]]

**Comment by cmajors-genscape** [comment]
I realized I was running version 2.2. After upgrading to version 2.5 I am no longer experiencing issues.
